# Generated by Django 4.1.5 on 2023-01-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=150)),
                ("nombre", models.TextField()),
                ("apellido_paterno", models.TextField()),
                ("apellido_materno", models.TextField()),
                ("dni", models.CharField(max_length=8)),
                ("publicado", models.BooleanField()),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_nacimiento", models.DateTimeField(auto_now=True)),
                ("estado", models.TextField()),
            ],
        ),
    ]
